[Issue #24] Fix for crossfaded out clips not being stopped
Unity-Technologies/SimpleAnimation pull request #32
Opened 2018-03-23 23:51 UTC by davidg-unity

Long due refactor of StateInfo to fix hard-to-debug state management and fix issue with Faded out clips not stopping.

2018-03-26 19:11 UTC, romainf-unity requested changes
Very good refactoring. A few comments that needs clarifications, but mostly approved.

2018-03-26 19:11 UTC, romainf-unity commented on Assets/SimpleAnimationComponent/SimpleAnimationPlayable_States.cs
> +            return (float)m_States[index].speed;
I don't think the cast is necessary.

2018-03-26 19:11 UTC, romainf-unity commented on Assets/SimpleAnimationComponent/SimpleAnimationPlayable_States.cs
> +            float speed = (float)m_States[index].speed;
I don't think the cast is necessary here too.

2018-03-26 19:25 UTC, davidg-unity commented on Assets/SimpleAnimationComponent/SimpleAnimationPlayable.cs
> +            float speed = (float)state.speed;
I'm pretty sure this cast is useless now.

2018-03-26 19:40 UTC, davidg-unity commented on Assets/SimpleAnimationComponent/SimpleAnimationPlayable_States.cs
> +            m_Playable.SetDone(false);
The play state is handled only in the Update Loop (executed in PrepareFrame), to avoid external modifications happening at any time during the frame

2018-03-26 19:40 UTC, davidg-unity commented on Assets/SimpleAnimationComponent/SimpleAnimationPlayable_States.cs
> +            return (float)m_States[index].speed;
Indeed, it's a leftover

2018-03-26 21:51 UTC, romainf-unity commented on Assets/SimpleAnimationComponent/SimpleAnimationPlayable_States.cs
> +            m_Playable.SetDone(false);
Play and Pause aren't affected by that?

2018-03-26 22:16 UTC, davidg-unity commented on Assets/SimpleAnimationComponent/SimpleAnimationPlayable_States.cs
> +            m_Time = newTime;
I merged SetTime with ResetTime

2018-03-27 15:35 UTC, romainf-unity approved these changes
LGTM!

2018-03-27 15:36 UTC, merged